services:
  app:
    container_name: app
#    entrypoint: ["/usr/local/go/bin/go", "run", "cmd/api/main.go"]
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    stdin_open: true
    restart: always
    environment:
      APP_ENV: dev
    volumes:
      - .:/application/
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    platform: linux/amd64
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - app-mysql-volume:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  app-mysql-volume:
