package persist

import "app/internal/domain/entity"

// to be autogenerated
func userFields(u *entity.User) []any {
	return []any{&u.ID, &u.FirstName, &u.LastName, &u.Email, &u.Active}
}

func accountFields(a *entity.Account) []any {
	return []any{&a.ID, &a.UserID, &a.Type, &a.Balance}
}

func transferFields(a *entity.Transfer) []any {
	return []any{&a.ID, &a.From, &a.To, &a.Amount}
}
